# Generated by Django 5.1 on 2025-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, default='', help_text='The logo of the company.', max_length=255, verbose_name='Company Logo'),
        ),
    ]
