# Generated by Django 5.1 on 2024-12-13 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=False)),
                ('mod_time_genotp', models.IntegerField(default=False)),
                ('email', models.CharField(db_comment='Email', max_length=255)),
                ('isVerified', models.BooleanField(db_column='isVerified', default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when EmailOTP object was originally created', verbose_name='Created on')),
            ],
        ),
    ]
