# Generated by Django 5.1 on 2024-12-16 04:58

from django.db import migrations

def create_groups_and_permissions(apps, schema_editor):
    # Get the Group and Permission models
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Define group names and their respective permissions
    groups_data = [
        {
            "name": "Admin",
            "permissions": [
                "add_user", "change_user", "delete_user", "view_user",
                "add_group", "change_group", "delete_group", "view_group"
            ],
        },
        {
            "name": "Manager",
            "permissions": [
                "change_user", "view_user"
            ],
        },
        {
            "name": "Employee",
            "permissions": [
                "view_user"
            ],
        },
    ]

    # Clear existing groups that match the names of the groups we are about to create
    group_names = [group_data["name"] for group_data in groups_data]
    Group.objects.filter(name__in=group_names).delete()

    for group_data in groups_data:
        # Create or get the group, now that previous data is cleared
        group, created = Group.objects.get_or_create(name=group_data["name"])
        if created:  # Only assign permissions if the group was newly created
            # Fetch the permissions based on their codenames
            permissions = Permission.objects.filter(codename__in=group_data["permissions"])
            group.permissions.set(permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),  # Specify the previous migration as a dependency
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
