# Generated by Django 5.1 on 2024-12-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_address_company_created_by_and_more'),
        ('projects', '0002_project_company_userprojectrel_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(help_text='The company this project belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(help_text='The list of users this project belongs to.', null=True, related_name='projects', through='projects.UserProjectRel', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
