# Generated by Django 5.1 on 2024-12-12 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_company_alter_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(help_text='The list of users this project belongs to.', related_name='projects', through='projects.UserProjectRel', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
