# Generated by Django 5.1 on 2024-12-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='nameAnlageAuszen',
            field=models.CharField(blank=True, default='', verbose_name='nameAnlageAuszen'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='seitenBezeichnung',
            field=models.CharField(blank=True, default='Seite', verbose_name='seitenBezeichnung'),
        ),
    ]
