# Generated by Django 5.1 on 2024-12-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectsettings_nameanlageauszen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltEmail',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltEmail'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltFax',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltFax'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltLocation',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltLocation'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltName',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltName'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltPhone',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltPhone'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltPostalCode',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltPostalCode'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltStreet',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='companyAltStreet'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='projektLocation',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='projektLocation'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='projektPostalCode',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='projektPostalCode'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='projektStreet',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='projektStreet'),
        ),
    ]
