# Generated by Django 5.1 on 2024-12-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectsettings_companyaltemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizontalloadpile',
            name='row_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pile',
            name='row_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soillayer',
            name='row_index',
            field=models.IntegerField(default=0),
        ),
    ]
