# Generated by Django 5.1 on 2024-12-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_horizontalloadpile_aslaengs_pile_federsteifigkeit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='runHorBemessung',
        ),
    ]
