# Generated by Django 5.1 on 2024-12-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_projectsettings_runhorbemessung'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='runHorBemessung',
            field=models.BooleanField(blank=True, default=True, verbose_name='runHorBemessung'),
        ),
    ]
