# Generated by Django 5.1 on 2024-12-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_pile_pfahltyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='BetonZyl',
            field=models.FloatField(blank=True, default=25, verbose_name='BetonZyl'),
        ),
        migrations.AddField(
            model_name='pile',
            name='einzelAusnutzung',
            field=models.FloatField(blank=True, default=1, verbose_name='einzelAusnutzung'),
        ),
        migrations.AddField(
            model_name='pile',
            name='einzelExzentrizitaet',
            field=models.FloatField(blank=True, default=0.1, verbose_name='einzelExzentrizitaet'),
        ),
        migrations.AddField(
            model_name='pile',
            name='einzelKnickLaenge',
            field=models.FloatField(blank=True, default=0, verbose_name='einzelKnickLaenge'),
        ),
        migrations.AddField(
            model_name='pile',
            name='einzelMaximaleBohrtiefe',
            field=models.FloatField(blank=True, default=100, verbose_name='einzelMaximaleBohrtiefe'),
        ),
        migrations.AddField(
            model_name='pile',
            name='einzelMindestEindringung',
            field=models.FloatField(blank=True, default=2.5, verbose_name='einzelMindestEindringung'),
        ),
    ]
