# Generated by Django 5.1 on 2024-12-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_pile_betonzyl_pile_einzelausnutzung_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprofile',
            old_name='PfahlTyp',
            new_name='pfahlTyp',
        ),
    ]
