# Generated by Django 5.1 on 2024-12-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_soillayer_maxelementweite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprofile',
            old_name='pfahlTyp',
            new_name='PfahlTyp',
        ),
    ]
