# Generated by Django 5.1 on 2024-12-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_pfahltyp_soilprofile_pfahltyp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilprofile',
            name='PfahlTyp',
        ),
    ]
