# Generated by Django 5.1 on 2024-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_soilprofile_pfahltyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilprofile',
            name='pfahlTyp',
            field=models.IntegerField(blank=True, choices=[(0, 'Jac-S'), (1, 'Jac-O'), (2, 'Jac-B'), (3, 'Jac-V'), (4, 'Bohrpfahl'), (5, 'Atlas'), (6, 'Fundex'), (7, 'VGS'), (14, 'Betonfertigrammpfahl'), (15, 'Stahlrohrrammpfahl, hb=0.8; hs=0.6'), (16, 'Fundex'), (17, 'Atlas-FDP')], default=4, verbose_name='pfahlTyp'),
        ),
    ]
