# Generated by Django 5.1 on 2024-12-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_soilprofile_pfahltyp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='SpitzendruckMittelung',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='WinkelAusProfilen',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='gegenRaeumlichenEP',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='ksNichtReduzieren',
        ),
    ]
