# Generated by Django 5.1 on 2024-12-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_projectsettings_spitzendruckmittelung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='SpitzendruckMittelung',
            field=models.BooleanField(blank=True, default=False, verbose_name='SpitzendruckMittelung'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='WinkelAusProfilen',
            field=models.BooleanField(blank=True, default=False, verbose_name='WinkelAusProfilen'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='gegenRaeumlichenEP',
            field=models.BooleanField(blank=True, default=True, verbose_name='gegenRaeumlichenEP'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='ksNichtReduzieren',
            field=models.BooleanField(blank=True, default=False, verbose_name='ksNichtReduzieren'),
        ),
    ]
