# Generated by Django 5.1 on 2024-12-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectsettings_spitzendruckmittelung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='Knicklaenge',
            field=models.FloatField(blank=True, default=0, verbose_name='Knicklaenge'),
        ),
    ]
