# Generated by Django 5.1 on 2024-12-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectsettings_knicklaenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='Norm',
            field=models.FloatField(blank=True, default=1, verbose_name='Norm'),
        ),
    ]
