# Generated by Django 5.1 on 2024-12-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectsettings_norm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='Norm',
        ),
    ]
