# Generated by Django 5.1 on 2024-12-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_projectsettings_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='Norm',
            field=models.IntegerField(blank=True, default=1, verbose_name='Norm'),
        ),
    ]
