# Generated by Django 5.1 on 2024-12-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectsettings_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='MaxLaenge',
            field=models.IntegerField(blank=True, default=100, verbose_name='MaxLaenge'),
        ),
    ]
