# Generated by Django 5.1 on 2024-12-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_projectsettings_maxlaenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pile',
            name='BetonZyl',
        ),
    ]
