# Generated by Django 5.1 on 2024-12-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_pile_betonzyl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='BetonZyl',
            field=models.IntegerField(blank=True, default=25, verbose_name='BetonZyl'),
        ),
    ]
