# Generated by Django 5.1 on 2024-12-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_pile_betonzyl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pile',
            name='PfahlAnzahl',
        ),
    ]
