# Generated by Django 5.1 on 2024-12-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_remove_pile_pfahlanzahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='PfahlAnzahl',
            field=models.IntegerField(blank=True, default=1, verbose_name='PfahlAnzahl'),
        ),
    ]
