# Generated by Django 5.1 on 2024-12-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_pile_pfahlanzahl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='einzelAusnutzung',
            field=models.IntegerField(blank=True, default=1, verbose_name='einzelAusnutzung'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelKnickLaenge',
            field=models.IntegerField(blank=True, default=0, verbose_name='einzelKnickLaenge'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelMaximaleBohrtiefe',
            field=models.IntegerField(blank=True, default=100, verbose_name='einzelMaximaleBohrtiefe'),
        ),
    ]
