# Generated by Django 5.1 on 2024-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_pile_einzelausnutzung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='SeiteVonSeiten',
            field=models.IntegerField(blank=True, default=0, verbose_name='SeiteVonSeiten'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='UKKotenInTabelle',
            field=models.IntegerField(blank=True, default=1, verbose_name='UKKotenInTabelle'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='UebersichtQuer',
            field=models.IntegerField(blank=True, default=1, verbose_name='UebersichtQuer'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='erstelleEinzelnachweise',
            field=models.IntegerField(blank=True, default=1, verbose_name='erstelleEinzelnachweise'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='erstelleUebersichtAuszen',
            field=models.IntegerField(blank=True, default=1, verbose_name='erstelleUebersichtAuszen'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='erstellegrafikAuszen',
            field=models.IntegerField(blank=True, default=1, verbose_name='erstellegrafikAuszen'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='erstellegrafikInnen',
            field=models.IntegerField(blank=True, default=1, verbose_name='erstellegrafikInnen'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='seitenStartNummer',
            field=models.IntegerField(blank=True, default=1, verbose_name='seitenStartNummer'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='zeichneNachweislinien',
            field=models.IntegerField(blank=True, default=1, verbose_name='zeichneNachweislinien'),
        ),
    ]
