# Generated by Django 5.1 on 2024-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_projectsettings_seitevonseiten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='useErhoehung',
            field=models.IntegerField(blank=True, default=0, verbose_name='useErhoehung'),
        ),
    ]
