# Generated by Django 5.1 on 2024-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_projectsettings_useerhoehung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='FuszBeeinfluszung',
            field=models.IntegerField(blank=True, default=0, verbose_name='FuszBeeinfluszung'),
        ),
    ]
