# Generated by Django 5.1 on 2024-12-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_projectsettings_fuszbeeinfluszung'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.CharField(default='', help_text='The pdf url of the project.', max_length=255, verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='project',
            name='xml',
            field=models.CharField(default='', help_text='The xml url of the project.', max_length=255, verbose_name='XML'),
        ),
    ]
