# Generated by Django 5.1 on 2024-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_pdf_project_xml'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horizontalloadcase',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_hloadcase_name'),
        ),
        migrations.AddConstraint(
            model_name='horizontalloadpile',
            constraint=models.UniqueConstraint(fields=('case', 'Pname'), name='unique_hloadcase_hloadname'),
        ),
        migrations.AddConstraint(
            model_name='pile',
            constraint=models.UniqueConstraint(fields=('project', 'Pname'), name='unique_project_pname'),
        ),
        migrations.AddConstraint(
            model_name='soilprofile',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_soilprofile_name'),
        ),
    ]
