# Generated by Django 5.1 on 2024-12-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_horizontalloadcase_unique_project_hloadcase_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadcase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='runHorBemessung',
            field=models.BooleanField(blank=True, default=False, verbose_name='runHorBemessung'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
