# Generated by Django 5.1 on 2025-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_alter_horizontalloadpile_aslaengs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='AsLaengs',
            field=models.FloatField(default=None, null=True, verbose_name='AsLaengs'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='AsLaengsCalc',
            field=models.FloatField(default=None, null=True, verbose_name='AsLaengsCalc'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='AsQuer',
            field=models.FloatField(default=None, null=True, verbose_name='AsQuer'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='AsQuerCalc',
            field=models.FloatField(default=None, null=True, verbose_name='AsQuerCalc'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='BewTyp',
            field=models.FloatField(default=None, null=True, verbose_name='BewTyp'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Eps0',
            field=models.FloatField(default=None, null=True, verbose_name='Eps0'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Eps1',
            field=models.FloatField(default=None, null=True, verbose_name='Eps1'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='KoteUeberdrueckt',
            field=models.FloatField(default=None, null=True, verbose_name='KoteUeberdrueckt'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='MMax',
            field=models.FloatField(default=None, null=True, verbose_name='MMax'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='MxMax',
            field=models.FloatField(default=None, null=True, verbose_name='MxMax'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='MyMax',
            field=models.FloatField(default=None, null=True, verbose_name='MyMax'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Nachweisgruppe',
            field=models.FloatField(default=None, null=True, verbose_name='Nachweisgruppe'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='QMax',
            field=models.FloatField(default=None, null=True, verbose_name='QMax'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='QxMax',
            field=models.FloatField(default=None, null=True, verbose_name='QxMax'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='QyMax',
            field=models.FloatField(default=None, null=True, verbose_name='QyMax'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='wOben',
            field=models.FloatField(default=None, null=True, verbose_name='wOben'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='wxOben',
            field=models.FloatField(default=None, null=True, verbose_name='wxOben'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='wyOben',
            field=models.FloatField(default=None, null=True, verbose_name='wyOben'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='EzuR',
            field=models.FloatField(default=None, null=True, verbose_name='EzuR'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Federsteifigkeit',
            field=models.FloatField(default=None, null=True, verbose_name='Federsteifigkeit'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='GesamtBohrLaenge',
            field=models.FloatField(default=None, null=True, verbose_name='GesamtBohrLaenge'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Nachweisgruppe',
            field=models.FloatField(default=None, null=True, verbose_name='Nachweisgruppe'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='PfahlVolumen',
            field=models.FloatField(default=None, null=True, verbose_name='PfahlVolumen'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='R_d',
            field=models.FloatField(default=None, null=True, verbose_name='R_d'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='R_d_Min',
            field=models.FloatField(default=None, null=True, verbose_name='R_d_Min'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Rb_k',
            field=models.FloatField(default=None, null=True, verbose_name='Rb_k'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Rs_k',
            field=models.FloatField(default=None, null=True, verbose_name='Rs_k'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Setzung',
            field=models.FloatField(default=None, null=True, verbose_name='Setzung'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='delta_Laenge',
            field=models.FloatField(default=None, null=True, verbose_name='delta_Laenge'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='laenge_mit',
            field=models.FloatField(default=None, null=True, verbose_name='laenge_mit'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='laenge_ohne',
            field=models.FloatField(default=None, null=True, verbose_name='laenge_ohne'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='usedQbk002',
            field=models.FloatField(default=None, null=True, verbose_name='usedQbk002'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='usedQbk003',
            field=models.FloatField(default=None, null=True, verbose_name='usedQbk003'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='usedQbk01',
            field=models.FloatField(default=None, null=True, verbose_name='usedQbk01'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='usedQsk',
            field=models.FloatField(default=None, null=True, verbose_name='usedQsk'),
        ),
    ]
