# Generated by Django 5.1 on 2025-01-02 05:09

from django.db import migrations, models

def clean_0_to_none(apps, schema_editor):
    Pile = apps.get_model('projects', 'Pile')
    
    Pile.objects.filter(Federsteifigkeit=0).update(Federsteifigkeit=None)
    Pile.objects.filter(Nachweisgruppe=0).update(Nachweisgruppe=None)
    Pile.objects.filter(R_d=0).update(R_d=None)
    Pile.objects.filter(R_d_Min=0).update(R_d_Min=None)
    Pile.objects.filter(Rb_k=0).update(Rb_k=None)
    Pile.objects.filter(Rs_k=0).update(Rs_k=None)
    Pile.objects.filter(Setzung=0).update(Setzung=None)
    Pile.objects.filter(laenge_mit=0).update(laenge_mit=None)
    Pile.objects.filter(laenge_ohne=0).update(laenge_ohne=None)
    Pile.objects.filter(EzuR=0).update(EzuR=None)
    Pile.objects.filter(GesamtBohrLaenge=0).update(GesamtBohrLaenge=None)
    Pile.objects.filter(PfahlVolumen=0).update(PfahlVolumen=None)
    Pile.objects.filter(delta_Laenge=0).update(delta_Laenge=None)

    SoilLayer = apps.get_model('projects', 'SoilLayer')
    
    SoilLayer.objects.filter(usedQsk=0).update(usedQsk=None)
    SoilLayer.objects.filter(usedQbk002=0).update(usedQbk002=None)
    SoilLayer.objects.filter(usedQbk003=0).update(usedQbk003=None)
    SoilLayer.objects.filter(usedQbk01=0).update(usedQbk01=None)

    HorizontalLoadPile = apps.get_model('projects', 'HorizontalLoadPile')
    
    HorizontalLoadPile.objects.filter(AsLaengs=0).update(AsLaengs=None)
    HorizontalLoadPile.objects.filter(AsLaengsCalc=0).update(AsLaengsCalc=None)
    HorizontalLoadPile.objects.filter(AsQuer=0).update(AsQuer=None)
    HorizontalLoadPile.objects.filter(AsQuerCalc=0).update(AsQuerCalc=None)
    HorizontalLoadPile.objects.filter(BewTyp=0).update(BewTyp=None)
    HorizontalLoadPile.objects.filter(Eps0=0).update(Eps0=None)
    HorizontalLoadPile.objects.filter(Eps1=0).update(Eps1=None)
    HorizontalLoadPile.objects.filter(KoteUeberdrueckt=0).update(KoteUeberdrueckt=None)
    HorizontalLoadPile.objects.filter(MMax=0).update(MMax=None)
    HorizontalLoadPile.objects.filter(MxMax=0).update(MxMax=None)
    HorizontalLoadPile.objects.filter(MyMax=0).update(MyMax=None)
    HorizontalLoadPile.objects.filter(Nachweisgruppe=0).update(Nachweisgruppe=None)
    HorizontalLoadPile.objects.filter(QMax=0).update(QMax=None)
    HorizontalLoadPile.objects.filter(QxMax=0).update(QxMax=None)
    HorizontalLoadPile.objects.filter(QyMax=0).update(QyMax=None)
    HorizontalLoadPile.objects.filter(wOben=0).update(wOben=None)
    HorizontalLoadPile.objects.filter(wxOben=0).update(wxOben=None)
    HorizontalLoadPile.objects.filter(wyOben=0).update(wyOben=None)

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_alter_horizontalloadpile_aslaengs_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_0_to_none)
    ]
