# Generated by Django 5.1 on 2025-01-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_soillayer_maxelementweite_alter_soillayer_cuep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hgkx',
            field=models.FloatField(blank=True, null=True, verbose_name='Hgkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hgky',
            field=models.FloatField(blank=True, null=True, verbose_name='Hgky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hqkx',
            field=models.FloatField(blank=True, null=True, verbose_name='Hqkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hqky',
            field=models.FloatField(blank=True, null=True, verbose_name='Hqky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mgkx',
            field=models.FloatField(blank=True, null=True, verbose_name='Mgkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mgky',
            field=models.FloatField(blank=True, null=True, verbose_name='Mgky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mqkx',
            field=models.FloatField(blank=True, null=True, verbose_name='Mqkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mqky',
            field=models.FloatField(blank=True, null=True, verbose_name='Mqky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='OKBodenBiegung',
            field=models.FloatField(blank=True, null=True, verbose_name='OKBodenBiegung'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='gammaStaendigV',
            field=models.FloatField(blank=True, null=True, verbose_name='gammaStaendigV'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='gammaVeraenderlichV',
            field=models.FloatField(blank=True, null=True, verbose_name='gammaVeraenderlichV'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='PfahlAchsAbstandxD',
            field=models.FloatField(blank=True, null=True, verbose_name='PfahlAchsAbstandxD'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='PfahlAnzahl',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='PfahlAnzahl'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='PfahlTyp',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='PfahlTyp'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelzulaessigeSetzungCm',
            field=models.FloatField(blank=True, null=True, verbose_name='einzelzulaessigeSetzungCm'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='prozentualerMantelAnteil',
            field=models.FloatField(blank=True, null=True, verbose_name='prozentualerMantelAnteil'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='ESoben',
            field=models.FloatField(blank=True, null=True, verbose_name='ESoben'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='ESunten',
            field=models.FloatField(blank=True, null=True, verbose_name='ESunten'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='FuszAbsetzbar',
            field=models.BooleanField(default=False, null=True, verbose_name='FuszAbsetzbar'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='IstEindringRelevant',
            field=models.BooleanField(default=False, null=True, verbose_name='IstEindringRelevant'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='bodenArt',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='bodenArt'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='bodenSchichtColor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='bodenSchichtColor'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='gammaBoden',
            field=models.FloatField(blank=True, null=True, verbose_name='gammaBoden'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='gammaStrichBoden',
            field=models.FloatField(blank=True, null=True, verbose_name='gammaStrichBoden'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='phi',
            field=models.FloatField(blank=True, null=True, verbose_name='phi'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qc',
            field=models.FloatField(blank=True, null=True, verbose_name='qc'),
        ),
    ]
