# Generated by Django 5.1 on 2025-01-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_horizontalloadpile_hgkx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Grundwasser',
            field=models.FloatField(verbose_name='Grundwasser'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Pname',
            field=models.CharField(max_length=64, verbose_name='Pile'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='gkz',
            field=models.FloatField(verbose_name='gkz'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='qkz',
            field=models.FloatField(verbose_name='qkz'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='AEHoehe',
            field=models.FloatField(verbose_name='Drilling level'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='AlternativeCharakteristischeLastZ',
            field=models.FloatField(verbose_name='AlternativeCharakteristischeLastZ'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='AlternativeDesignLastZ',
            field=models.FloatField(verbose_name='AlternativeDesignLastZ'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Hochwert',
            field=models.FloatField(verbose_name='Hochwert'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Pname',
            field=models.CharField(help_text='Unique load point name for this project', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='Rechtswert',
            field=models.FloatField(verbose_name='Rechtswert'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='SollDurchmesser',
            field=models.FloatField(verbose_name='SollDurchmesser'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='SollPfahlOberKante',
            field=models.FloatField(verbose_name='SollPfahlOberKante'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelAusnutzung',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='einzelAusnutzung'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelExzentrizitaet',
            field=models.FloatField(blank=True, default=0.1, null=True, verbose_name='einzelExzentrizitaet'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelKnickLaenge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='einzelKnickLaenge'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelMaximaleBohrtiefe',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='einzelMaximaleBohrtiefe'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelMindestEindringung',
            field=models.FloatField(blank=True, default=2.5, null=True, verbose_name='einzelMindestEindringung'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='endKote',
            field=models.FloatField(verbose_name='endKote'),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='grundwasserStand',
            field=models.FloatField(verbose_name='grundwasserStand'),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Profile Name'),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='pfahlTyp',
            field=models.IntegerField(blank=True, choices=[(0, 'Jac-S'), (1, 'Jac-O'), (2, 'Jac-B'), (3, 'Jac-V'), (4, 'Bohrpfahl'), (5, 'Atlas'), (6, 'Fundex'), (7, 'VGS'), (14, 'Betonfertigrammpfahl'), (15, 'Stahlrohrrammpfahl, hb=0.8; hs=0.6'), (16, 'Fundex'), (17, 'Atlas-FDP')], default=4, null=True, verbose_name='pfahlTyp'),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='startKote',
            field=models.FloatField(verbose_name='startKote'),
        ),
    ]
