# Generated by Django 5.1 on 2025-01-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_remove_horizontalloadpile_gammastaendigv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hgkx',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Hgkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hgky',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Hgky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hqkx',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Hqkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Hqky',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Hqky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mgkx',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Mgkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mgky',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Mgky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mqkx',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Mqkx'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Mqky',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Mqky'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='OKBodenBiegung',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='OKBodenBiegung'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='PfahlTyp',
            field=models.CharField(blank=True, default='bp', max_length=16, null=True, verbose_name='PfahlTyp'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='einzelzulaessigeSetzungCm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='einzelzulaessigeSetzungCm'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='prozentualerMantelAnteil',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='prozentualerMantelAnteil'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='ESoben',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ESoben'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='ESunten',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ESunten'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='FuszAbsetzbar',
            field=models.BooleanField(default=True, null=True, verbose_name='FuszAbsetzbar'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='bodenSchichtColor',
            field=models.CharField(blank=True, default='D8D8D8', max_length=10, null=True, verbose_name='bodenSchichtColor'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='cuEP',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='cuEP'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='cuk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='cuk'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='deltaVonPhi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='deltaVonPhi'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='gammaBoden',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='gammaBoden'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='gammaStrichBoden',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='gammaStrichBoden'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='phi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='phi'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qbk002',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qbk002'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qbk003',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qbk003'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qbk01',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qbk01'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qc',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qc'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qsk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qsk'),
        ),
    ]
