# Generated by Django 5.1 on 2025-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_alter_horizontalloadpile_grundwasser'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='LangsbewehrungBugelbewehrung',
            field=models.FloatField(default=1, null=True, verbose_name='LangsbewehrungBugelbewehrung'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='MmaxSchubbemessung',
            field=models.FloatField(default=1, null=True, verbose_name='MmaxSchubbemessung'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='einzelMaximaleBohrtiefe',
            field=models.FloatField(default=1, null=True, verbose_name='einzelMaximaleBohrtiefe'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='falsermInner',
            field=models.IntegerField(default=1, null=True, verbose_name='falsermInner'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='mantelreibungcu',
            field=models.BooleanField(default=True, null=True, verbose_name='mantelreibungcu'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='mantelreibungqc',
            field=models.BooleanField(default=True, null=True, verbose_name='mantelreibungqc'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='maxBugelbewehrung',
            field=models.FloatField(default=1, null=True, verbose_name='maxBugelbewehrung'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='maxLangsbewehrung',
            field=models.FloatField(default=1, null=True, verbose_name='maxLangsbewehrung'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='reinforcingSteel',
            field=models.IntegerField(default=1, null=True, verbose_name='reinforcingSteel'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='selectedConcreteCover',
            field=models.FloatField(default=1, null=True, verbose_name='selectedConcreteCover'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='spritzendruckcu',
            field=models.BooleanField(default=True, null=True, verbose_name='spritzendruckcu'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='spritzendruckqc',
            field=models.BooleanField(default=True, null=True, verbose_name='spritzendruckqc'),
        ),
    ]
