# Generated by Django 5.1 on 2025-01-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_alter_project_name_project_unique_company_proj_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='soillayer',
            name='PfahlTyp',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='PfahlTyp'),
        ),
    ]
