# Generated by Django 5.1 on 2025-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_soillayer_pfahltyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='Eindringung',
            field=models.FloatField(default=None, null=True, verbose_name='Eindringung'),
        ),
        migrations.AddField(
            model_name='pile',
            name='Soll_UK_Pfahl',
            field=models.FloatField(default=None, null=True, verbose_name='Soll_UK_Pfahl'),
        ),
        migrations.AddField(
            model_name='pile',
            name='bohrLaenge',
            field=models.FloatField(default=None, null=True, verbose_name='bohrLaenge'),
        ),
        migrations.AddField(
            model_name='pile',
            name='notwendigASLaengs',
            field=models.FloatField(default=None, null=True, verbose_name='notwendigASLaengs'),
        ),
        migrations.AddField(
            model_name='pile',
            name='notwendigBewehrungsLaenge',
            field=models.FloatField(default=None, null=True, verbose_name='notwendigBewehrungsLaenge'),
        ),
    ]
