# Generated by Django 5.1 on 2025-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_pile_eindringung_pile_soll_uk_pfahl_pile_bohrlaenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pile',
            name='Eindringung',
        ),
        migrations.RemoveField(
            model_name='pile',
            name='bohrLaenge',
        ),
        migrations.RemoveField(
            model_name='pile',
            name='notwendigASLaengs',
        ),
        migrations.RemoveField(
            model_name='pile',
            name='notwendigBewehrungsLaenge',
        ),
        migrations.AddField(
            model_name='pile',
            name='AsLaengs',
            field=models.FloatField(default=None, null=True, verbose_name='AsLaengs'),
        ),
        migrations.AddField(
            model_name='pile',
            name='BewBZWLieferlaenge',
            field=models.FloatField(default=None, null=True, verbose_name='BewBZWLieferlaenge'),
        ),
        migrations.AddField(
            model_name='pile',
            name='EindringTiefe',
            field=models.FloatField(default=None, null=True, verbose_name='EindringTiefe'),
        ),
        migrations.AddField(
            model_name='pile',
            name='BohrLaenge',
            field=models.FloatField(default=None, null=True, verbose_name='BohrLaenge'),
        ),
    ]
