# Generated by Django 5.1 on 2025-02-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_remove_pile_eindringung_remove_pile_bohrlaenge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horizontalloadpile',
            options={'ordering': ['row_index']},
        ),
        migrations.AlterModelOptions(
            name='pile',
            options={'ordering': ['row_index']},
        ),
        migrations.AlterModelOptions(
            name='soillayer',
            options={'ordering': ['row_index']},
        ),
    ]
