# Generated by Django 5.1 on 2025-02-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_remove_projectsettings_langsbewehrungbugelbewehrung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horizontalloadpile',
            name='gammaStaendigV',
        ),
        migrations.RemoveField(
            model_name='horizontalloadpile',
            name='gammaVeraenderlichV',
        ),
    ]
