# Generated by Django 5.1 on 2025-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_remove_horizontalloadpile_gammastaendigv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltEmail',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltEmail'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltFax',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltFax'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltLocation',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltLocation'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltName',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltName'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltPhone',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltPhone'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltPostalCode',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltPostalCode'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='companyAltStreet',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='companyAltStreet'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='projektLocation',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='projektLocation'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='projektPostalCode',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='projektPostalCode'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='projektStreet',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='projektStreet'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='useErhoehung',
            field=models.IntegerField(blank=True, default=2, verbose_name='useErhoehung'),
        ),
    ]
