# Generated by Django 5.1 on 2025-02-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_horizontalloadpile_panoberkante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='pAnOberkante',
            field=models.FloatField(default=1.9, verbose_name='pAnOberkante'),
        ),
    ]
