# Generated by Django 5.1 on 2025-02-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_alter_horizontalloadpile_panoberkante'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='MindestEindringung',
            field=models.FloatField(default=0.75, verbose_name='MindestEindringung'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='StandardPfahlTyp',
            field=models.CharField(default='bp', verbose_name='StandardPfahlTyp'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='bemesseHorizontal',
            field=models.BooleanField(blank=True, default=True, verbose_name='bemesseHorizontal'),
        ),
    ]
