# Generated by Django 5.1 on 2025-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_projectsettings_mindesteindringung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soillayer',
            name='qskStern',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qskStern'),
        ),
        migrations.AddField(
            model_name='soillayer',
            name='qskZug',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='qskZug'),
        ),
        migrations.AddField(
            model_name='soillayer',
            name='tauNk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='tauNk'),
        ),
    ]
