# Generated by Django 5.1 on 2025-02-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_soillayer_qskstern_soillayer_qskzug_soillayer_taunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='prozentualerMantelAnteil',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='prozentualerMantelAnteil'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='Betondeckung',
            field=models.FloatField(default=120, verbose_name='Betondeckung'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='MaxBuegel',
            field=models.FloatField(default=8, verbose_name='MaxBuegel'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='MaxLaengs',
            field=models.FloatField(default=16, verbose_name='MaxLaengs'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='MinLaengsAbstand',
            field=models.FloatField(default=100, verbose_name='MinLaengsAbstand'),
        ),
    ]
