# Generated by Django 5.1 on 2025-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_alter_pile_prozentualermantelanteil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='default_company_info',
            field=models.BooleanField(blank=True, default=True, verbose_name='default_company_info'),
        ),
    ]
