# Generated by Django 5.1 on 2025-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_projectsettings_companyaltlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='Schrittweite',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Schrittweite'),
        ),
    ]
