# Generated by Django 5.1 on 2025-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_alter_pile_aehoehe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='gkz',
            field=models.FloatField(null=True, verbose_name='gkz'),
        ),
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='qkz',
            field=models.FloatField(null=True, verbose_name='qkz'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='endKote',
            field=models.FloatField(null=True, verbose_name='endKote'),
        ),
    ]
