# Generated by Django 5.1 on 2025-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_alter_horizontalloadpile_gkz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='Betondeckung',
            field=models.FloatField(default=100, verbose_name='Betondeckung'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='MaxBuegel',
            field=models.FloatField(default=10, verbose_name='MaxBuegel'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='MaxLaengs',
            field=models.FloatField(default=20, verbose_name='MaxLaengs'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='MvonMaxfuerSchub',
            field=models.FloatField(default=50, verbose_name='MvonMaxfuerSchub'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='SeiteVonSeiten',
            field=models.IntegerField(blank=True, default=1, verbose_name='SeiteVonSeiten'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='WinkelAusProfilen',
            field=models.BooleanField(blank=True, default=True, verbose_name='WinkelAusProfilen'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='ksNichtReduzieren',
            field=models.BooleanField(blank=True, default=True, verbose_name='ksNichtReduzieren'),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='grundwasserStand',
            field=models.FloatField(null=True, verbose_name='grundwasserStand'),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='startKote',
            field=models.FloatField(null=True, verbose_name='startKote'),
        ),
    ]
