# Generated by Django 5.1 on 2025-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_alter_projectsettings_betondeckung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='AlternativeCharakteristischeMinLastZ',
            field=models.FloatField(default=0, verbose_name='AlternativeCharakteristischeMinLastZ'),
        ),
        migrations.AlterField(
            model_name='pile',
            name='AlternativeDesignMinLastZ',
            field=models.FloatField(default=0, verbose_name='AlternativeDesignMinLastZ'),
        ),
    ]
