# Generated by Django 5.1 on 2025-02-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_alter_pile_alternativecharakteristischeminlastz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalloadpile',
            name='Pname',
            field=models.CharField(max_length=64, null=True, verbose_name='Pile'),
        ),
    ]
