# Generated by Django 5.1 on 2025-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_alter_horizontalloadpile_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='PfahlAchsAbstandxD',
            field=models.FloatField(blank=True, default=3, null=True, verbose_name='PfahlAchsAbstandxD'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='FuszAbsetzbar',
            field=models.BooleanField(default=False, null=True, verbose_name='FuszAbsetzbar'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='MaxElementWeite',
            field=models.FloatField(blank=True, default=0.1, null=True, verbose_name='MaxElementWeite'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='bodenArt',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='bodenArt'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='cuk',
            field=models.FloatField(blank=True, default='NaN', null=True, verbose_name='cuk'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='gammaBoden',
            field=models.FloatField(blank=True, default=19, null=True, verbose_name='gammaBoden'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='gammaStrichBoden',
            field=models.FloatField(blank=True, default=19, null=True, verbose_name='gammaStrichBoden'),
        ),
        migrations.AlterField(
            model_name='soillayer',
            name='qc',
            field=models.FloatField(blank=True, default='NaN', null=True, verbose_name='qc'),
        ),
    ]
