# Generated by Django 5.1 on 2025-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_alter_pile_pfahlachsabstandxd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soillayer',
            name='deltaVonPhi',
            field=models.FloatField(blank=True, default=0.67, null=True, verbose_name='deltaVonPhi'),
        ),
    ]
