# Additional key mapping that store name translations between XML and model…
PROJECT_SETTING_KEYS_MAPPING = {
    'name'                    : '_ProjektName',
    'runHorBemessung'         : '_runHorBemessung',
    'AbtreppungsWinkelRad'    : '_AbtreppungsWinkelRad',
    'AchsabstandGleicherTiefe': '_AchsabstandGleicherTiefe',
    'AuslastungProzent'       : '_AuslastungProzent',
    'Beeinflussungsweite'     : '_Beeinflussungsweite',
    'EAErhoehungProzent'      : '_EAErhoehungProzent',
    'Exzentrizitaet'          : '_Exzentrizitaet',
    'FuszBeeinfluszung'       : '_FuszBeeinfluszung',
    'FuszErhoehungProzent'    : '_FuszErhoehungProzent',
    'Knicklaenge'             : '_Knicklaenge',
    'MantelErhoehungProzent'  : '_MantelErhoehungProzent',
    'MindestEinbindung'       : '_MindestEinbindung',
    'MindestPfahllaenge'      : '_MindestPfahllaenge',
    'Norm'                    : '_Norm',
    'Schrittweite'            : '_Schrittweite',
    'SpitzendruckMittelung'   : '_SpitzendruckMittelung',
    'WinkelAusProfilen'       : '_WinkelAusProfilen',
    'bemesseHorizontal'       : '_bemesseHorizontal',
    'gammaDruck'              : '_gammaDruck',
    'gammaStaendig'           : '_gammaStaendig',
    'gammaVeraenderlich'      : '_gammaVeraenderlich',
    'gammaZug'                : '_gammaZug',
    'gegenRaeumlichenEP'      : '_gegenRaeumlichenEP',
    'ksNichtReduzieren'       : '_ksNichtReduzieren',
    'useErhoehung'            : '_useErhoehung',
    'zulaessigeSetzungCm'     : '_zulaessigeSetzungCm',
    'BetonZyl'                : '_BetonZyl',
    'Betondeckung'            : '_Betondeckung',
    'KopfEinbindung'          : '_KopfEinbindung',
    'MaxLaenge'               : '_MaxLaenge',
    'projektLocation'         : '_projektLocation',
    'projektPostalCode'       : '_projektPostalCode',
    'projektStreet'           : '_projektStreet',
    'companyAltEmail'         : '_companyAltEmail',
    'companyAltFax'           : '_companyAltFax',
    'companyAltLocation'      : '_companyAltLocation',
    'companyAltName'          : '_companyAltName',
    'companyAltPhone'         : '_companyAltPhone',
    'companyAltPostalCode'    : '_companyAltPostalCode',
    'companyAltStreet'        : '_companyAltStreet',
    'companyAltLogo'          : '_companyAltLogo',
    'nameAnlageAuszen'        : '_nameAnlageAuszen',
    'seitenBezeichnung'       : '_seitenBezeichnung',
    'seitenStartNummer'       : '_seitenStartNummer',
    'SeiteVonSeiten'          : '_SeiteVonSeiten',
    'erstelleUebersichtAuszen': '_erstelleUebersichtAuszen',
    'UebersichtQuer'          : '_UebersichtQuer',
    'erstelleEinzelnachweise' : '_erstelleEinzelnachweise',
    'zeichneNachweislinien'   : '_zeichneNachweislinien',
    'UKKotenInTabelle'        : '_UKKotenInTabelle',
    'erstellegrafikAuszen'    : '_erstellegrafikAuszen',
    'erstellegrafikInnen'     : '_erstellegrafikInnen',

    'qskQcAb0'          : '_qskQcAb0',
    'qbkQcAb0'          : '_qbkQcAb0',
    'qskCukAb0'         : '_qskCukAb0',
    'qbkCukAb0'         : '_qbkCukAb0',
    'MaxLaengs'         : '_MaxLaengs',
    'MaxBuegel'         : '_MaxBuegel',
    'MinLaengsAbstand'  : '_MinLaengsAbstand',
    'MindestEindringung': '_MindestEindringung',
    'Stahlsorte'        : '_Stahlsorte',
    'StandardPfahlTyp'  : '_StandardPfahlTyp',
    'MvonMaxfuerSchub'  : '_MvonMaxfuerSchub',
}


PILE_INPUT_KEYS_MAPPING = {
    "Pname"                               : "_Pname",
    "AEHoehe"                             : "_AEHoehe",
    "AlternativeCharakteristischeLastZ"   : "_AlternativeCharakteristischeLastZ",
    "AlternativeCharakteristischeMinLastZ": "_AlternativeCharakteristischeMinLastZ",
    "AlternativeDesignLastZ"              : "_AlternativeDesignLastZ",
    "AlternativeDesignMinLastZ"           : "_AlternativeDesignMinLastZ",
    "BetonZyl"                            : "_BetonZyl",
    "BodenProfil"                         : "_BodenProfil",
    "Hochwert"                            : "_Hochwert",
    "PfahlAchsAbstandxD"                  : "_PfahlAchsAbstandxD",
    "PfahlAnzahl"                         : "_PfahlAnzahl",
    "PfahlTyp"                            : "_PfahlTyp",
    "Rechtswert"                          : "_Rechtswert",
    "SollDurchmesser"                     : "_SollDurchmesser",
    "SollPfahlOberKante"                  : "_SollPfahlOberKante",
    "einzelAusnutzung"                    : "_einzelAusnutzung",
    "einzelExzentrizitaet"                : "_einzelExzentrizitaet",
    "einzelKnickLaenge"                   : "_einzelKnickLaenge",
    "einzelMaximaleBohrtiefe"             : "_einzelMaximaleBohrtiefe",
    "einzelMindestEindringung"            : "_einzelMindestEindringung",
    "einzelzulaessigeSetzungCm"           : "_einzelzulaessigeSetzungCm",
    "prozentualerMantelAnteil"            : "_prozentualerMantelAnteil"
}

PILE_OUTPUT_KEYS_MAPPING = {
    "Federsteifigkeit"  : "_Federsteifigkeit",
    "Nachweisgruppe"    : "_Nachweisgruppe",
    "R_d"               : "_R_d",
    "R_d_Min"           : "_R_d_Min",
    "Rb_k"              : "_Rb_k",
    "Rs_k"              : "_Rs_k",
    "Setzung"           : "_Setzung",
    "laenge_mit"        : "_laenge_mit",
    "laenge_ohne"       : "_laenge_ohne",
    "EzuR"              : "_EzuR",
    "GesamtBohrLaenge"  : "_GesamtBohrLaenge",
    "PfahlVolumen"      : "_PfahlVolumen",
    "delta_Laenge"      : "_delta_Laenge",
    "Soll_UK_Pfahl"     : "_Soll_UK_Pfahl",
    "BohrLaenge"        : "_BohrLaenge",
    "AsLaengs"          : "_AsLaengs",
    "BewBZWLieferlaenge": "_BewBZWLieferlaenge",
    "EindringTiefe"     : "_EindringTiefe"
}

SOIL_PROFILE_INPUT_KEYS_MAPPING = {
    'soil_table_name' : '_profilName',
    'PfahlTyp'        : '_PfahlTyp',
    'grundwasserStand': '_grundwasserStand',
    'startKote'       : '_startKote',
    'list_soil_layers': 'alleBodenSchichten',
}


SOIL_PROFILE_OUTPUT_KEYS_MAPPING = {
    'pfahlTyp'        : '_pfahlTyp',
    'list_soil_layers': '_schichten',
}


SOIL_LAYER_INPUT_KEYS_MAPPING = {
    'endKote'            : '_endKote',
    'bodenArt'           : '_bodenArt',
    'ESoben'             : '_ESoben',
    'ESunten'            : '_ESunten',
    'FuszAbsetzbar'      : '_FuszAbsetzbar',
    'IstEindringRelevant': '_IstEindringRelevant',
    'MaxElementWeite'    : '_MaxElementWeite',
    'cuEP'               : '_cuEP',
    'cuk'                : '_cuk',
    'deltaVonPhi'        : '_deltaVonPhi',
    'gammaBoden'         : '_gammaBoden',
    'gammaStrichBoden'   : '_gammaStrichBoden',
    'phi'                : '_phi',
    'qbk002'             : '_qbk002',
    'qbk003'             : '_qbk003',
    'qbk01'              : '_qbk01',
    'qc'                 : '_qc',
    'qsk'                : '_qsk',
    'qskStern'           : '_qskStern',
    'bodenSchichtColor'  : '_bodenSchichtColor',
    'tauNk'              : '_tauNk',
    'qskZug'             : '_qskZug'
}


SOIL_LAYER_OUTPUT_KEYS_MAPPING = {
    'PfahlTyp'  : '_Pfahltyp',
    'usedQsk'   : '_usedQsk',
    'usedQbk002': '_usedQbk002',
    'usedQbk003': '_usedQbk003',
    'usedQbk01' : '_usedQbk01'
}


HORIZONTAL_LOAD_CASE_INPUT_KEYS_MAPPING = {
    'hlc_table_name': 'hTabelleName',
    'list_hlcs'     : 'hLastPunkte',
}


HORIZONTAL_LOAD_POINT_INPUT_KEYS_MAPPING = {
    'Pname'              : '_Pname',
    'Grundwasser'        : '_Grundwasser',
    'Hgkx'               : '_Hgkx',
    'Hgky'               : '_Hgky',
    'Hqkx'               : '_Hqkx',
    'Hqky'               : '_Hqky',
    'Mgkx'               : '_Mgkx',
    'Mgky'               : '_Mgky',
    'Mqkx'               : '_Mqkx',
    'Mqky'               : '_Mqky',
    'OKBodenBiegung'     : '_OKBodenBiegung',
    'gkz'                : '_gkz',
    'pAnOberkante'       : '_pAnOberkante',
    'qkz'                : '_qkz',
}


HORIZONTAL_LOAD_POINT_OUTPUT_KEYS_MAPPING = {
    'AsLaengs'        : '_AsLaengs',
    'AsLaengsCalc'    : '_AsLaengsCalc',
    'AsLaengsMin'     : '_AsLaengsMin',
    'AsQuer'          : '_AsQuer',
    'AsQuerCalc'      : '_AsQuerCalc',
    'AsSchubMin'      : '_AsSchubMin',
    'Berechnung'      : '_Berechnung',
    'BerechnungOK'    : '_BerechnungOK',
    'BewTyp'          : '_BewTyp',
    'Eps0'            : '_EpsO',
    'Eps1'            : '_Eps1',
    'KoteUeberdrueckt': '_KoteUeberdrueckt',
    'MMax'            : '_MMax',
    'MxMax'           : '_MxMax',
    'MyMax'           : '_MyMax',
    'Nachweisgruppe'  : '_Nachweisgruppe',
    'QMax'            : '_QMax',
    'QxMax'           : '_QxMax',
    'QyMax'           : '_QyMax',
    'wOben'           : '_wOben',
    'wxOben'          : '_wxOben',
    'wyOben'          : '_wyOben',
    'MdKopf'          : '_MdKopf',
    'MdKopfx'         : '_MdKopfx',
    'MdKopfy'         : '_MdKopfy',
    'wStrichKopf'     : '_wStrichKopf',
    'wStrichKopfx'    : '_wStrichKopfx',
    'wStrichKopfy'    : '_wStrichKopfy',
}

CUSTOMER_INFO_COMPANY_KEYS_MAPPING = {
    "name"       : "_companyName",
    "address"    : "_companyStreet",
    "location"   : "_companyLocation",
    "postal_code": "_companyPostalCode",
    "email"      : "_companyEmail",
    "logo"       : "_companyLogo",
    "phone"      : "_companyPhone",
    "fax"        : "_companyFax",
}

USER_INFO_KEYS_MAPPING = {
    "full_name": "_userName",
    "phone"    : "_userPhone",
    "email"    : "_userEmail",
}

STRUCTRURE_XML_ELEMENT_KEYS = [
    "InputDaten",
    "projektInfo",
    "pfaehle",
    "LastPunktInputList",
    "LastPunktInput",
    "boden",
    "alleBodenProfile",
    "BodenProfilDaten",
    "alleBodenSchichten",
    "BodenSchichtDaten",
    "hLasten",
    "hTabellen",
    "HLastInputTabelle",
    "hLastPunkte",
    "HLastPunktInput",
    "_columnInput",
    "_customerInfo",
    "_userInfo",
    "userKeyHorizontal",
    "userKey",
    "userMailAddress",
    "_companyInvoiceStyle",
]

CALCULATION_PROJECT_SETTING_KEYS = {
    'name',
    'runHorBemessung',
    'AbtreppungsWinkelRad',
    'AchsabstandGleicherTiefe',
    'AuslastungProzent',
    'Beeinflussungsweite',
    'EAErhoehungProzent',
    'Exzentrizitaet',
    'FuszBeeinfluszung',
    'FuszErhoehungProzent',
    'MantelErhoehungProzent',
    'MindestEinbindung',
    'MindestPfahllaenge',
    'MvonMaxfuerSchub',
    'Norm',
    'Schrittweite',
    'SpitzendruckMittelung',
    'WinkelAusProfilen',
    'bemesseHorizontal',
    'gammaDruck',
    'gammaStaendig',
    'gammaVeraenderlich',
    'gammaZug',
    'gegenRaeumlichenEP',
    'ksNichtReduzieren',
    'qbkCukAb0',
    'qbkQcAb0',
    'qskCukAb0',
    'qskQcAb0',
    'useErhoehung',
    'zulaessigeSetzungCm',
    'BetonZyl',
    'Betondeckung',
    'KopfEinbindung',
    'MaxBuegel',
    'MaxLaenge',
    'MaxLaengs',
    'MinLaengsAbstand',
    'MindestEindringung',
    'Stahlsorte',
    'StandardPfahlTyp',
    'projektLocation',
    'projektStreet',
    'projektPostalCode',
    'companyAltName',
    'companyAltLocation',
    'companyAltStreet',
    'companyAltPostalCode',
    'companyAltLogo',
    'nameAnlageAuszen',
    'seitenBezeichnung',
    'seitenStartNummer',
    'SeiteVonSeiten',
    'erstelleUebersichtAuszen',
    'UebersichtQuer',
    'erstelleEinzelnachweise',
    'zeichneNachweislinien',
    'UKKotenInTabelle',
    'erstellegrafikAuszen',
    'erstellegrafikInnen'
}

ORDER_SETTING_KEYS = [
    '_ProjektName',
    '_runHorBemessung',
    '_AbtreppungsWinkelRad',
    '_AchsabstandGleicherTiefe',
    '_AuslastungProzent',
    '_Beeinflussungsweite',
    '_EAErhoehungProzent',
    '_Exzentrizitaet',
    '_FuszBeeinfluszung',
    '_FuszErhoehungProzent',
    '_MantelErhoehungProzent',
    '_MindestEinbindung',
    '_MindestPfahllaenge',
    '_MvonMaxfuerSchub',
    '_Norm',
    '_Schrittweite',
    '_SpitzendruckMittelung',
    '_WinkelAusProfilen',
    '_bemesseHorizontal',
    '_gammaDruck',
    '_gammaStaendig',
    '_gammaVeraenderlich',
    '_gammaZug',
    '_gegenRaeumlichenEP',
    '_ksNichtReduzieren',
    '_qbkCukAb0',
    '_qbkQcAb0',
    '_qskCukAb0',
    '_qskQcAb0',
    '_useErhoehung',
    '_zulaessigeSetzungCm',
    '_BetonZyl',
    '_Betondeckung',
    '_KopfEinbindung',
    '_MaxBuegel',
    '_MaxLaenge',
    '_MaxLaengs',
    '_MinLaengsAbstand',
    '_MindestEindringung',
    '_Stahlsorte',
    '_StandardPfahlTyp',
    '_projektLocation',
    '_projektStreet',
    '_projektPostalCode',
    '_companyAltName',
    '_companyAltLocation',
    '_companyAltStreet',
    '_companyAltPostalCode',
    '_companyAltLogo',
    '_nameAnlageAuszen',
    '_seitenBezeichnung',
    '_seitenStartNummer',
    '_SeiteVonSeiten',
    '_erstelleUebersichtAuszen',
    '_UebersichtQuer',
    '_erstelleEinzelnachweise',
    '_zeichneNachweislinien',
    '_UKKotenInTabelle',
    '_erstellegrafikAuszen',
    '_erstellegrafikInnen',
]

ORDER_PILE_KEYS = [
    "_Pname",
    "_AEHoehe",
    "_AlternativeCharakteristischeLastZ",
    "_AlternativeCharakteristischeMinLastZ",
    "_AlternativeDesignLastZ",
    "_AlternativeDesignMinLastZ",
    "_BetonZyl",
    "_BodenProfil",
    "_Hochwert",
    "_PfahlAchsAbstandxD",
    "_PfahlAnzahl",
    "_PfahlTyp",
    "_Rechtswert",
    "_SollDurchmesser",
    "_SollPfahlOberKante",
    "_einzelAusnutzung",
    "_einzelExzentrizitaet",
    "_einzelKnickLaenge",
    "_einzelMaximaleBohrtiefe",
    "_einzelMindestEindringung",
    "_einzelzulaessigeSetzungCm",
    "_prozentualerMantelAnteil",
]

ORDER_SOIL_PROFILE_KEYS = [
    "_profilName",
    "pfahlTyp",
    "grundwasserStand",
    "startKote",
]

ORDER_SOIL_LAYER_KEYS = [
    "_endKote",
    "_bodenArt",
    "_ESoben",
    "_ESunten",
    "_FuszAbsetzbar",
    "_IstEindringRelevant",
    "_MaxElementWeite",
    "_cuEP",
    "_cuk",
    "_deltaVonPhi",
    "_gammaBoden",
    "_gammaStrichBoden",
    "_phi",
    "_qbk002",
    "_qbk003",
    "_qbk01",
    "_qc",
    "_qsk",
    '_qskStern',
    '_bodenSchichtColor',
    '_tauNk',
    '_qskZug'
]

JSON_TO_XML_KEYS_MAPPING = {
    **PROJECT_SETTING_KEYS_MAPPING,
    **PILE_INPUT_KEYS_MAPPING,
    **PILE_OUTPUT_KEYS_MAPPING,
    **SOIL_LAYER_INPUT_KEYS_MAPPING,
    **SOIL_LAYER_OUTPUT_KEYS_MAPPING,
    **SOIL_PROFILE_INPUT_KEYS_MAPPING,
    **SOIL_PROFILE_OUTPUT_KEYS_MAPPING,
    **HORIZONTAL_LOAD_CASE_INPUT_KEYS_MAPPING,
    **HORIZONTAL_LOAD_POINT_INPUT_KEYS_MAPPING,
    **HORIZONTAL_LOAD_POINT_OUTPUT_KEYS_MAPPING
}

XML_TO_JSON_KEYS_MAPPING = {v: k for k, v in JSON_TO_XML_KEYS_MAPPING.items()}
XML_KEYS = list(XML_TO_JSON_KEYS_MAPPING.keys()) \
    + [val for _key, val in CUSTOMER_INFO_COMPANY_KEYS_MAPPING.items()] \
    + [val for _key, val in USER_INFO_KEYS_MAPPING.items()] \
    + STRUCTRURE_XML_ELEMENT_KEYS


PILE_KEY_XLSX_2_JSON_MAPPING = {
      "Lastpunkt"         : "Pname",
      "Pfahltyp"          : "PfahlTyp",
      "Pfahlanzahl"       : "PfahlAnzahl",
      "Pfahlachsabstand"  : "PfahlAchsAbstandxD",
      "Bohrebene"         : "AEHoehe",
      "Oberkante Pfahl"   : "SollPfahlOberKante",
      "x"                 : "Rechtswert",
      "y"                 : "Hochwert",
      "Pfahldurchmesser"  : "SollDurchmesser",
    r"E_{k}"              : "AlternativeCharakteristischeLastZ",
    r"E_{d}"              : "AlternativeDesignLastZ",
      "Bodenprofil"       : "BodenProfil",
      "Mindesteindringung": "einzelMindestEindringung",
      "zul. Setzung"      : "einzelzulaessigeSetzungCm",
    #   "BetonZyl"          : "BetonZyl",
      "Mantelanteil"      : "prozentualerMantelAnteil",

    # Output
    # r"R_{s,k}"                      : "Rs_k",
    # r"R_{b,k}"                      : "Rb_k",
    # r"R_{d}"                        : "R_d",
    #   "Nachweis E/R"                : "EzuR",
    #   "L erforderlich mit Einfluss" : "laenge_mit",
    #   "L erforderlich ohne Einfluss": "laenge_ohne",
    #   "Delta L"                     : "delta_Laenge",
    #   "Soll UK Pfahl"               : "Soll_UK_Pfahl",
    #   "Bohrlänge"                   : "BohrLaenge",
    #   "Gesamtbohrlänge"             : "GesamtBohrLaenge",
    #   "Setzung"                     : "Setzung",
    #   "Federsteifigkeit"            : "Federsteifigkeit",
    #   "Nachweisgruppe"              : "Nachweisgruppe",
    #   "Erf. As Längs"               : "AsLaengs",
    #   "Erf. Bewehrungslänge"        : "BewBZWLieferlaenge",
    #   "Eindringung"                 : "EindringTiefe",
    #   "Pfahlvolumen"                : "PfahlVolumen"

    # "einzelAusnutzung"         : "einzelAusnutzung",
    # "einzelExzentrizitaet"     : "einzelExzentrizitaet",
    # "einzelKnickLaenge"        : "einzelKnickLaenge",
    # "einzelMaximaleBohrtiefe"  : "einzelMaximaleBohrtiefe",
    # "R_d_Min"                  : "R_d_Min",
    # "nachweisER"               : "EzuR",
    # "deltaL"                   : "delta_Laenge",
    # "sollPfahlUnterKante"      : "Soll_UK_Pfahl",
    # "bohrLaenge"               : "BohrLaenge",
    # "gesamtBohrLaenge"         : "GesamtBohrLaenge",
    # "notwendigASLaengs"        : "AsLaengs",
    # "notwendigBewehrungsLaenge": "BewBZWLieferlaenge",
    # "Pfahltyp"                 : "",
}

PILE_KEY_JSON_2_XLSX_MAPPING = {v: k for k, v in PILE_KEY_XLSX_2_JSON_MAPPING.items()}

EMPTY_XLSX_PILE = {k: "" for k, v in PILE_KEY_XLSX_2_JSON_MAPPING.items()}

SOIL_KEY_XLSX_2_JSON_MAPPING = {
    # soil profile
    "name"                : "name",
    "Grundwasserstand"    : "grundwasserStand",
    "Startkote"           : "startKote",
    "soil_layers"         : "soil_layers",

    # soil layer
    "Endkote"             : "endKote",
    "Bodenart"            : "bodenArt",
    "Farbe"               : "bodenSchichtColor",
    "qc"                  : "qc",
    "c_{u,k}"             : "cuk",
    "q_{s,k,i}"           : "qsk",
    "q_{b,k} s/D=0,02"    : "qbk002",
    "q_{b,k} s/D=0,03"    : "qbk003",
    "q_{b,k} s/D=0,1"     : "qbk01",
    "Phi"                 : "phi",
    "Fußabsetzbarkeit"    : "FuszAbsetzbar",
    "Eindringungsrelevant": "IstEindringRelevant",
    "Delta von Phi"       : "deltaVonPhi",
    "Gamma"               : "gammaBoden",
    "Gamma Strich"        : "gammaStrichBoden",
    "Es oben"             : "ESoben",
    "Es unten"            : "ESunten",
    "Elementlänge"        : "MaxElementWeite",
    "c_{u,ep}"            : "cuEP",
    # "Pfahltyp"            : "pfahlTyp",
}
SOIL_KEY_JSON_2_XLSX_MAPPING = {v: k for k, v in SOIL_KEY_XLSX_2_JSON_MAPPING.items()}
EMPTY_XLSX_SOIL_LAYER = {k: "" for k, v in list(SOIL_KEY_XLSX_2_JSON_MAPPING.items())[4:]}

H_LOAD_KEY_XLSX_2_JSON_MAPPING = {
    "Lastpunkt"          : "Pname",
    "V_{g,k,z}"          : "gkz",
    "V_{q,k,z}"          : "qkz",
    "H_{g,k,x}"          : "Hgkx",
    "H_{q,k,x}"          : "Hqkx",
    "M_{g,k,y}"          : "Mgky",
    "M_{q,k,y}"          : "Mqky",
    "H_{g,k,y}"          : "Hgky",
    "H_{q,k,y}"          : "Hqky",
    "M_{g,k,x}"          : "Mgkx",
    "M_{q,k,x}"          : "Mqkx",
    "OK Boden Biegung"   : "OKBodenBiegung",
    "Grundwasserstand"   : "Grundwasser",

    # Output
    # "Erf. As Längs"      : "AsLaengs",
    # "Rechn. As Längs"    : "AsLaengsCalc",
    # "Erf. As Quer"       : "AsQuer",
    # "Rechn. As Quer"     : "AsQuerCalc",
    # "Typ (Centrum)"      : "BewTyp",
    # "Betondehnung"       : "Eps0",
    # "Stahldehnung"       : "Eps1",
    # "Min. Kote Bewehrung": "KoteUeberdrueckt",
    # "|Max VEd|"          : "MMax",
    # "|Max ME,x,d|"       : "MxMax",
    # "|Max ME,y,d|"       : "MyMax",
    # "Nachweisgruppe"     : "NachweisGruppe",
    # "|Max MEd|"          : "QMax",
    # "|Max VE,x,d|"       : "QxMax",
    # "|Max VE,y,d|"       : "QyMax",
    # "w"                  : "wOben",
    # "wx"                 : "wxOben",
    # "wy"                 : "wyOben",
}
H_LOAD_KEY_JSON_2_XLSX_MAPPING = {v: k for k, v in H_LOAD_KEY_XLSX_2_JSON_MAPPING.items()}
EMPTY_XLSX_H_LOAD = {k: "" for k, v in H_LOAD_KEY_XLSX_2_JSON_MAPPING.items()}
